"""empty message

Revision ID: 6be7ebecd44a
Revises: None
Create Date: 2016-03-27 12:20:57.234577

"""

# revision identifiers, used by Alembic.
revision = '6be7ebecd44a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('essays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('spell_errors', sa.Text(), nullable=True),
    sa.Column('grammar_errors', sa.Text(), nullable=True),
    sa.Column('coherence', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('essays')
    ### end Alembic commands ###
